name: xarray-tutorial
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - cudf=23.10.01
  - python=3.10
  # for building website:
  - jupyter-book
  - pre-commit
  # for user interface
  - dask-labextension
  - jupyterlab
  - jupyterlab-myst
  - jupyter-resource-usage
  # for default notebook kernel:
  - cartopy
  - cf_xarray
  - dask
  - datashader
  - distributed
  - gcsfs
  - geoviews-core
  - gsw
  - hvplot
  - ipython
  - matplotlib-base
  - netcdf4
  - pint-xarray
  - pip
  - pydap
  - python-graphviz
  - pooch
  - rioxarray
  - scipy
  - sphinx-codeautolink
  - sphinx-exercise
  - sphinx-notfound-page
  - sphinxext-rediraffe
  - xarray
  - zarr
